
services:
  frontend:
    build:
      context: react-frontend
      dockerfile: Dockerfile
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - react-frontend/.env
    networks:
      - app-network

  backend:
    build:
      context: django-backend
      dockerfile: Dockerfile
    volumes: # Quitar en prod
      - ./django-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - django-backend/.env
    networks:
      - app-network

  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - app-network
    restart: unless-stopped

  # Uncomment and configure for production database
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: pointcloud
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:

volumes:
  jenkins_home:
  # Uncomment for persistent database storage
  # db-data:
