# Generated by Django 4.2.26 on 2025-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original filename of the point cloud', max_length=255)),
                ('file', models.FileField(help_text='Path to the uploaded .pts file', upload_to='pointclouds/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
                ('num_points', models.IntegerField(help_text='Total number of points in the cloud')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (bounds, intensity range, etc.)')),
            ],
            options={
                'verbose_name': 'Point Cloud',
                'verbose_name_plural': 'Point Clouds',
                'ordering': ['-upload_date'],
            },
        ),
    ]
