# Generated by Django 4.2.26 on 2025-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcloud',
            name='mesh_file',
            field=models.FileField(blank=True, help_text='Path to generated mesh file (.obj)', null=True, upload_to='pointclouds/'),
        ),
        migrations.AddField(
            model_name='pointcloud',
            name='mesh_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Mesh metadata (vertices count, triangles count, algorithm used)'),
        ),
    ]
